# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'runcommand_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.command_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.command_lineEdit.setObjectName("command_lineEdit")
        self.gridLayout_2.addWidget(self.command_lineEdit, 0, 0, 1, 2)
        self.path_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.gridLayout_2.addWidget(self.path_lineEdit, 1, 0, 1, 2)
        self.path_lable = QtWidgets.QLabel(self.widget)
        self.path_lable.setObjectName("path_lable")
        self.gridLayout_2.addWidget(self.path_lable, 2, 0, 1, 1)
        self.resul_lable = QtWidgets.QLabel(self.widget)
        self.resul_lable.setObjectName("resul_lable")
        self.gridLayout_2.addWidget(self.resul_lable, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(85, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.path_button = QtWidgets.QPushButton(self.widget)
        self.path_button.setObjectName("path_button")
        self.gridLayout_2.addWidget(self.path_button, 4, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(85, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 4, 3, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.command_lineEdit.setPlaceholderText(_translate("Form", "Command"))
        self.path_lineEdit.setPlaceholderText(_translate("Form", "Path"))
        self.path_lable.setText(_translate("Form", "Path:"))
        self.resul_lable.setText(_translate("Form", "Result:"))
        self.path_button.setText(_translate("Form", "Get Path"))
        self.pushButton_2.setText(_translate("Form", "Run Command"))
